receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    traces_index: simpleapp-traces
    metrics_index: simpleapp-metrics
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
