apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: simpleapp
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: simpleapp:k8s-test
          imagePullPolicy: Never
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: simpleapp-secrets
